server:
  port: 8897
logging:
  level:
    root: info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyinvest?useEncoding=true&characterEncoding=UTF-8
    hikari:
      connection-timeout: 10000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      username: root
      password:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Bangkok

  jackson:
    time-zone: Asia/Bangkok
    deserialization:
      adjust_dates_to_context_time_zone: true
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: "*"
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/manage"
      exposure:
        include: "metrics,health"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /api-swaggers.html
    enabled: true

app-config:
  keymanagement:
    url: http://localhost:9061
    allowAllCerts: false
  scbPartnerAPI:
    url: https://api-sandbox.partners.scb/partners/sandbox/    # Partner API dev system
    acceptLanguage: en                    # Currently only supported value is en
    apikey: l77e59998d177a49c591eba7b238974fd2
    apisecret: 02c353f9ae1e4d358e656e8924b4d86b
    resourceOwnerId: f35758c4-311b-4ff2-a109-b9ae846e7d46
    allowAllCerts: false     # Disable on production and required on production
    logType: BODY
    useMock: true
    mockProfile:
      citizen:
        cardType: "P1"
        citizenID: "0174095219768"
      alien:
        cardType: "P7"
        alienId: "0467325911226"
      passport:
        cardType: "P8"
        partnerID: "AA123456789"
        countryCode: "US"
    mockDeeplink:
      deeplink:
        data:
          callbackUrl: "scbeasysim://login/6d0a4642-77cb-4372-b595-029608bb5927"
        status:
          code: 1000
          description: "Success"